/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'what-is-chim',
    'installing',
    'how-it-works',
    'cache-behavior',
    'configuration',
    'security',
    'hooks',
    'windows',
    'faq',
    'terminology',
    'external-links',
    {
      type: 'category',
      label: 'Fetchers',
      collapsible: false,
      items: [
        {type: 'autogenerated', dirName: 'fetchers'},
      ],
    },
    {
      type: 'category',
      label: 'CLI Commands',
      collapsible: false,
      items: [
        {type: 'autogenerated', dirName: 'commands'},
      ],
    },
  ],
};

module.exports = sidebars;
